from enum import Enum

class EventStatus(str, Enum):
    PUBLISHED = "PUBLISHED"
    DRAFT = "DRAFT"
    CANCELLED = "CANCELLED"
    REGISTRATION_CLOSED = "REGISTRATION_CLOSED"
    FINISHED = "FINISHED"